export const actionTypes = {
    SET_TOKEN:"SET_TOKEN",
    GET_PLAYLIST:"GET_PLAYLIST",
    SET_USER: "SET_USERS",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_PLAYING: "SET_PLAYING",
    SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
    SET_PLAYER_STATE: "SET_PLAYER_STATE",
}